GameModeSetupConfig {
 m_Prefabs {
  GameModeSetupConfigEntry "{66236770124E3427}" {
   m_Prefab "{884C37A5E43BECAC}Prefabs/MP/Modes/PvE/7Cav_GameMode_PvE.et"
  }
 }
 m_MissionHeader SCR_MissionHeaderScenarioFramework "{662367703B3899AA}" {
  World "{02752C0725066FA3}Worlds/7Cav_PvE_Ruha.ent"
  m_sName "Saber Shield"
  m_sAuthor "S3 Dev"
  m_sGameMode "PvE"
  m_iPlayerCount 64
  m_eEditableGameFlags 3
  m_eDefaultGameFlags 3
 }
}