SCR_MissionHeader {
 World "{7C6AA82784F9F94E}Worlds/7Cav_SB_Novka.ent"
 m_sName "7Cav Sandbox Novka"
 m_sAuthor "S3 Dev"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_bIsSavingEnabled 1
}