SCR_MissionHeader {
 World "{C505316BA86AFA32}Worlds/FactionTesting.ent"
 m_sName "Testing Faction Setup"
 m_sAuthor "7Cav S3 DEV"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_bIsSavingEnabled 1
}