SCR_MissionHeader "{5C525D8EA73AAF30}" {
 World "{75942BA649CB55DF}Worlds/KeeneTest.ent"
 m_sName "<Insert world name>"
 m_sAuthor "<Insert your name>"
 m_sDescription "<Insert world description>"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_bIsSavingEnabled 1
}